<?php

namespace Blog\BlogBundle\Repository;

/**
 * loginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class loginRepository extends \Doctrine\ORM\EntityRepository
{
}
